version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: app/backend/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./app/database:/app/database
      - ./app/backend:/app/backend
    environment:
      - SECRET_KEY=your-secret-key-here
      - ENVIRONMENT=development
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: app/frontend/Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ./app/frontend:/app/frontend
    environment:
      - API_URL=http://backend:8000
      - ENVIRONMENT=development
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
